import { load } from 'cheerio';

export const DEFAULT_PRODUCT_PAGE_TIMEOUT_MS = 10_000;

export interface PrisjaktOffer {
  store: string;
  storeId?: string;
  price: number;
}

export class PrisjaktPriceParseError extends Error {
  constructor(value: string) {
    super(`Failed to parse Prisjakt price: ${JSON.stringify(value)}`);
    this.name = 'PrisjaktPriceParseError';
  }
}

export class PrisjaktProductParseError extends Error {
  constructor(reason: string) {
    super(`Failed to parse Prisjakt product page: ${reason}`);
    this.name = 'PrisjaktProductParseError';
  }
}

export function parsePrisjaktProductTitle(html: string): string {
  const $ = load(html);
  const title = $('h1')
    .map((_, element) => $(element).text().replace(/\s+/g, ' ').trim())
    .get()
    .find((candidate) => candidate.length > 0);

  if (!title) {
    throw new PrisjaktProductParseError(
      'product title was not found in an h1 element',
    );
  }

  return title;
}

/**
 * Extract the store offers rendered on a Prisjakt product page.
 *
 * The offer list has a stable data-test attribute, while its CSS classes are
 * generated by the site. An entry is only considered an offer when it has a
 * clickout link, a named store logo, and a price in the offer heading.
 */
export function parsePrisjaktProductOffers(html: string): PrisjaktOffer[] {
  const $ = load(html);
  const offers: PrisjaktOffer[] = [];

  $('[data-test="OfferListItem"]').each((_, element) => {
    const offer = $(element);
    const clickout = offer.find('[data-test="OfferClickoutButton"]').first();
    const store = offer
      .find('img[alt]')
      .map((__, image) => $(image).attr('alt')?.replace(/\s+/g, ' ').trim())
      .get()
      .find((name): name is string => Boolean(name));
    const priceText = offer
      .find('h1, h2, h3, h4, h5, h6')
      .map((__, heading) => $(heading).text().replace(/\s+/g, ' ').trim())
      .get()
      .find((text) => /(?:kr|sek)\b/i.test(text));
    let price: number | undefined;
    if (priceText !== undefined) {
      try {
        price = parsePriceToOre(priceText);
      } catch {
        return;
      }
    }

    if (clickout.length === 0 || store === undefined || price === undefined) {
      return;
    }

    const href = clickout.attr('href');
    const storeId = href?.match(/\/go-to-shop\/([^/?#]+)\/offer\//i)?.[1];

    offers.push({
      store,
      ...(storeId === undefined ? {} : { storeId }),
      price,
    });
  });

  return offers;
}

/** Convert a Swedish/Prisjakt currency display into whole Swedish öre. */
export function parsePriceToOre(value: string): number {
  if (typeof value !== 'string') {
    throw new PrisjaktPriceParseError(String(value));
  }

  const normalized = value
    .replace(/[\u00a0\u202f]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/\s*(?:sek|kr)\s*$/i, '');
  const match = normalized.match(
    /^(\d+|\d{1,3}(?:[ .]\d{3})+)(?:,(\d{1,2}))?$/,
  );

  if (match === null) {
    throw new PrisjaktPriceParseError(value);
  }

  const whole = Number(match[1].replace(/[ .]/g, ''));
  const decimal = match[2] ?? '';

  if (!Number.isSafeInteger(whole) || whole < 0) {
    throw new PrisjaktPriceParseError(value);
  }

  const priceInOre = whole * 100 + Number(decimal.padEnd(2, '0'));
  if (!Number.isSafeInteger(priceInOre)) {
    throw new PrisjaktPriceParseError(value);
  }

  return priceInOre;
}

export const parsePrisjaktPrice = parsePriceToOre;

export class PrisjaktProductFetchError extends Error {
  constructor(
    public readonly productUrl: string,
    reason: string,
    options?: ErrorOptions,
  ) {
    super(
      `Failed to fetch Prisjakt product page ${productUrl}: ${reason}`,
      options,
    );
    this.name = 'PrisjaktProductFetchError';
  }
}

export async function fetchPrisjaktProductPage(
  productUrl: string,
  timeoutMs = DEFAULT_PRODUCT_PAGE_TIMEOUT_MS,
): Promise<string> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);

  try {
    const response = await fetch(productUrl, { signal: controller.signal });

    if (!response.ok) {
      const status = response.statusText
        ? `${response.status} ${response.statusText}`
        : `${response.status}`;
      throw new PrisjaktProductFetchError(productUrl, `HTTP ${status}`);
    }

    return await response.text();
  } catch (error) {
    if (error instanceof PrisjaktProductFetchError) {
      throw error;
    }

    if (controller.signal.aborted) {
      throw new PrisjaktProductFetchError(
        productUrl,
        `request timed out after ${timeoutMs} ms`,
        { cause: error },
      );
    }

    const reason = error instanceof Error ? error.message : String(error);
    throw new PrisjaktProductFetchError(productUrl, reason, { cause: error });
  } finally {
    clearTimeout(timeout);
  }
}
